kind: Service
apiVersion: v1
metadata:
  name: manager
  labels:
    app: polyfea-webserver
spec:  
  selector:
    control-plane: controller-manager
  ports:
  - name: webserver
    protocol: TCP
    port: 80
    targetPort: http