apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  labels:
    app.kubernetes.io/name: webcomponent
    app.kubernetes.io/instance: webcomponent-sample
    app.kubernetes.io/part-of: polyfea-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: polyfea-controller
  name: webcomponent-sample
spec:
  microFrontend: microfrontend-sample
  element: "test-element"
  attributes:
    - name: "test-attribute"
      value: "test-value"
  displayRules:
    - anyOf:
      - path: /test
      - context-name: test
