/*
 * Polyfea Browser application
 *
 * This is the OpenAPI definition for the Polyfea endpoint serving the context information to the browser client. The client is requesting context information from the backend typically  when approaching the `<polyfea-context>` element. The context information is then used to render the UI of the application.
 *
 * API version: v1alpha1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package polyfea

// StaticConfigArea - Specification of the static configuration of the context area with specific name and path regex.
type StaticConfigArea struct {

	// Name of the context area.
	Name string `json:"name"`

	// The regular expression to match the path relative to base href to apply this context area.  If path is not provided then context area specification applies on any path. In case of the conflicts the first matching context area is used.
	Path string `json:"path,omitempty"`

	ContextArea ContextArea `json:"contextArea,omitempty"`
}

// AssertStaticConfigAreaRequired checks if the required fields are not zero-ed
func AssertStaticConfigAreaRequired(obj StaticConfigArea) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertContextAreaRequired(obj.ContextArea); err != nil {
		return err
	}
	return nil
}

// AssertStaticConfigAreaConstraints checks if the values respects the defined constraints
func AssertStaticConfigAreaConstraints(obj StaticConfigArea) error {
	return nil
}
